-- New Speeduino build components: sensors, passives, and accessories
-- Referenced in official Speeduino wiki and Wrench over Wallet build guides
-- Usage: wrangler d1 execute store_db --remote --file=./db/seed-new-components.sql
-- Local:  wrangler d1 execute store_db --local  --file=./db/seed-new-components.sql

-- ── NEW SENSORS ──────────────────────────────────────────────────────────

-- 3-bar external MAP sensor (for builds running >1.5 bar boost)
-- Referenced in choosing-sensors guide and Speeduino wiki hardware requirements
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('map-sensor-3bar','map-sensor-3bar','3-Bar MAP Sensor (External, 0–300 kPa)','3-Bar MAP','External MAP sensor for high-boost builds above 1.5 bar. Linear 0–5V output compatible with all Speeduino boards.','The on-board MPX4250 covers naturally aspirated and mildly boosted engines (up to approximately 1.5 bar boost / 250 kPa absolute). For builds running higher boost, an external 3-bar sensor is required. This sensor covers 0–300 kPa absolute (approximately 0–2 bar boost) with a linear 0–5V output compatible with any Speeduino board. Calibrate in TunerStudio under Tools → Calibrate Pressure Sensors by selecting the matching sensor type or entering custom linear values. Any 0–5V linear MAP sensor is supported by Speeduino firmware.',3800,'sensor','["v0.3","v0.4"]','MAP input pin on the Speeduino board','optional','[]','Beginner','5–10','["3-bar MAP sensor","3-pin connector pigtail (150mm)"]','["Vacuum hose","T-piece fitting"]',NULL,0,1,'{"Type":"Absolute pressure","Range":"0–300 kPa (0–2 bar boost)","Output":"0–5V linear","Supply voltage":"5V","Connector":"3-pin","Note":"For boost above ~1.5 bar; the on-board MPX4250 handles up to 1.5 bar boost"}',202);

-- Knock sensor (piezoelectric, M12 thread)
-- Referenced in choosing-sensors and common-tuning-mistakes guides
-- Speeduino wiki documents knock sensor support under hardware requirements
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('knock-sensor','knock-sensor-m12','Knock Sensor (Piezoelectric, M12 Thread)','Knock Sensor','Piezoelectric knock sensor for detonation protection. Connects directly to Speeduino knock input.','A flat-style piezoelectric knock sensor for detonation (knock) detection. Threaded into the engine block, it detects the characteristic vibration of detonation and outputs a signal the ECU uses to retard ignition timing before damage occurs. Strongly recommended for any build where ignition timing is being advanced towards MBT — especially on boosted engines where detonation can cause rapid damage within a single combustion event. Configure in TunerStudio under Tuning → Knock Settings. Includes a 2-pin connector pigtail for clean wiring.',2900,'sensor','["v0.3","v0.4"]','Knock input on the Speeduino board','optional','[]','Intermediate','5–10','["Piezoelectric knock sensor","2-pin connector pigtail (200mm)"]','["Mounting bolt (engine-specific thread)"]',NULL,0,1,'{"Type":"Piezoelectric resonant","Thread":"M12 x 1.25 or M12 x 1.5 (check engine fitment)","Connector":"2-pin flat (GM-style)","Resonant frequency":"~6 kHz","Compatible with":"Speeduino knock input"}',260);

-- Cam position sensor (Hall effect, 3-wire)
-- Required for sequential injection — referenced in Speeduino wiki hardware requirements
-- and choosing-sensors guide ("Cam position sensor — required for sequential injection")
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('cam-sensor-hall','cam-sensor-hall-3wire','Cam Position Sensor (Hall Effect, 3-Wire)','Cam Sensor','Hall effect cam sensor outputting 0–5V square wave. Required for full-sequential injection.','A 3-wire Hall effect camshaft position sensor that outputs a clean 0–5V digital square wave — directly readable by Speeduino without a VR conditioner. Required for full-sequential fuel injection (one injector fire per cylinder per cycle) and sequential ignition strategies. The cam signal lets Speeduino determine which stroke the engine is on, enabling precise per-cylinder timing. Compatible with existing cam reluctor wheels or paired with a trigger magnet. Configure the cam input in TunerStudio under Settings → Trigger Settings.',3200,'sensor','["v0.3","v0.4"]','Cam input pin on Speeduino board (RPM2)','optional','[]','Intermediate','5–10','["Hall effect cam position sensor","3-pin connector pigtail (200mm)"]','["Trigger magnet","Mounting bracket (engine-specific)"]',NULL,0,1,'{"Type":"Hall effect (digital output)","Output":"0–5V square wave","Supply voltage":"5–24V","Connector":"3-pin","Thread":"M12 x 1.5","Required for":"Sequential injection / sequential ignition"}',270);

-- ── NEW MODULES ──────────────────────────────────────────────────────────

-- Stepper IAC valve (4-wire) — works with DRV8825 driver already in store
-- Referenced in guides and Speeduino wiki (DRV8825 stepper mount on v0.4)
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('iac-stepper-valve','iac-stepper-valve-gm','Stepper IAC Valve (GM 4-Wire)','Stepper IAC','4-wire stepper idle air control valve. Pairs with the DRV8825 driver on v0.4 boards.','A GM-compatible 4-wire bipolar stepper motor idle air control (IAC) valve for smooth, precise idle speed management. The DRV8825 stepper driver module — which mounts directly on the v0.4 board — drives this valve under Speeduino firmware control. Stepper IAC valves provide accurate, repeatable idle control across the full temperature and load range, performing significantly better than simple on/off or single-wire PWM valves. Configure idle control in TunerStudio under Settings → Idle Settings.',4800,'module','["v0.4"]','DRV8825 stepper driver on the v0.4 board','optional','[{"idleControl":["stepper_4wire"],"boardFamily":["v0.4"]}]','Intermediate','5–10','["4-wire bipolar stepper IAC valve"]','["DRV8825 driver module (sold separately)","Wiring pigtail"]',NULL,0,1,'{"Type":"4-wire bipolar stepper motor IAC","Wires":"4 (two coil pairs)","Driver required":"DRV8825 stepper module","Board":"v0.4 (DRV8825 socket required)","Control":"Step/direction via Speeduino idle output"}',145);

-- ── NEW ACCESSORIES / PASSIVES ───────────────────────────────────────────

-- Flyback diodes 1N4007 (10-pack) — explicitly mentioned in boost control guide
-- "Use a flyback diode across the solenoid terminals to protect the ECU driver transistor"
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('flyback-diode-pack','flyback-diode-pack-1n4007','Flyback Diode Pack (1N4007, 10x)','Flyback Diodes','10x 1N4007 rectifier diodes for inductive load protection. One per solenoid or relay coil.','Any inductive load controlled by the ECU — boost control solenoid, idle air control valve, relay coil — generates a high-voltage spike when switched off. Without a flyback (freewheeling) diode, these spikes reach hundreds of volts and can destroy the ECU driver transistor in a single event. The 1N4007 silicon rectifier is the standard diode for this protection: wire one in reverse bias across each solenoid or relay coil. A pack of 10 covers a full build. Wire cathode (stripe) to the positive terminal of the solenoid.',700,'accessory','["v0.3","v0.4"]','Across each solenoid or relay coil in reverse bias','recommended','[]','Beginner','3–5','["10x 1N4007 silicon rectifier diodes"]','[]',NULL,0,1,'{"Type":"1N4007 silicon rectifier diode","Peak inverse voltage":"1000V","Forward current":"1A continuous","Package":"DO-41 axial leaded","Purpose":"Flyback / freewheeling protection for inductive loads"}',350);

-- 36-1 crank trigger wheel (tested pattern in Speeduino wiki, referenced in hardware reqs)
-- "Tested missing-tooth wheels currently are 4-1, 12-1, 36-1 and 60-2" (official wiki)
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('trigger-wheel-36-1','trigger-wheel-36-1-steel','36-1 Crank Trigger Wheel (Steel, Universal)','36-1 Trigger Wheel','Steel 36-1 trigger wheel for Speeduino crank position decoding. Confirmed supported trigger pattern.','The 36-1 (35 teeth plus 1 missing tooth) trigger wheel pattern is one of the most widely tested and supported patterns in Speeduino firmware, confirmed in the official documentation alongside 4-1, 12-1, and 60-2. Essential for engine conversions or builds where the OEM crank trigger wheel is incompatible or absent. Steel construction with a 60mm hub bore for machining to your crankshaft diameter or mounting on a custom adapter. Pair with a Hall effect or VR sensor — if using a VR sensor, the VR conditioner module is also required. Select the 36-1 decoder in TunerStudio under Settings → Trigger Settings.',3900,'accessory','["v0.3","v0.4"]','Crank sensor trigger input','optional','[]','Advanced','5–14','["36-1 steel crank trigger wheel (60mm hub bore)"]','["Hub adapter","Woodruff key","Mounting bolts","Crank sensor","VR conditioner (if using VR sensor)"]',NULL,0,1,'{"Tooth pattern":"36-1 (35 teeth + 1 missing)","Material":"Steel","Hub bore":"60mm (rebore or adapter for fitment)","Outer diameter":"~150mm","Speeduino firmware":"36-1 decoder (confirmed supported)"}',355);

-- GM 2-pin sensor pigtail pack — for CLT, IAT, and 2-pin MAP sensor connections
-- Mentioned in guides as commonly needed, saves sourcing hassle
INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('gm-pigtail-pack','gm-sensor-pigtail-pack','GM Sensor Pigtail Pack (2-Pin, 4x)','Sensor Pigtails','4x GM 2-pin Metripack connector pigtails for CLT, IAT, and MAP sensors. Pre-crimped, ready to splice.','A pack of four pre-crimped GM Metripack 150-series 2-pin connector pigtails, compatible with all standard GM-style CLT, IAT, and 2-pin MAP sensors. Each pigtail includes 200mm of wire for splicing or extending into your main harness. The single most common source of wiring delay on first builds is tracking down the correct sensor connectors. These are the correct connectors for the GM-style CLT and IAT sensors stocked in this store.',1400,'accessory','["v0.3","v0.4"]','CLT, IAT, and MAP sensor connections','optional','[]','Beginner','3–5','["4x GM 2-pin Metripack 150 connector pigtails (200mm leads)"]','[]',NULL,0,1,'{"Connector":"GM Metripack 150 (2-pin)","Quantity":"4 pigtails","Lead length":"200mm each","Compatible with":"GM CLT sensor, GM IAT sensor, 2-pin MAP sensors"}',360);

-- ── INVENTORY (new products at qty 50) ──────────────────────────────────

INSERT OR REPLACE INTO inventory (product_id, qty, updated_at) VALUES
  ('map-sensor-3bar',    50, datetime('now')),
  ('knock-sensor',       50, datetime('now')),
  ('cam-sensor-hall',    50, datetime('now')),
  ('iac-stepper-valve',  50, datetime('now')),
  ('flyback-diode-pack', 50, datetime('now')),
  ('trigger-wheel-36-1', 50, datetime('now')),
  ('gm-pigtail-pack',    50, datetime('now'));
