-- Seed products + inventory (run after schema.sql or migrate-products-full.sql)
-- Usage: wrangler d1 execute store_db --remote --file=./db/seed-inventory.sql
-- Local:  wrangler d1 execute store_db --local --file=./db/seed-inventory.sql

-- ── BOARDS ──────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('v03-pcb','speeduino-v03-pcb','Speeduino v0.3 PCB (DIY Kit)','v0.3 Board','Screw-terminal ECU shield — prototype-friendly, easy to debug. Ideal for first builds.','The v0.3 Speeduino shield uses screw terminals for all I/O connections, making it the easiest board to wire and troubleshoot. Perfect for bench testing, learning, and prototype builds. Requires an Arduino Mega 2560 (sold separately or as a bundle).',12900,'board','["v0.3"]','Stacks onto Arduino Mega 2560','required','[{"boardFamily":["v0.3"]}]','Intermediate','3–7','["Speeduino v0.3 PCB","Through-hole component kit","Assembly guide (PDF)"]','["Arduino Mega 2560","Sensors","Wideband controller","Enclosure"]',NULL,1,1,'{"Board version":"v0.3","I/O connection":"Screw terminals","Injector outputs":"4 (batch / semi-sequential)","Ignition outputs":"4 (wasted spark / COP)","VR conditioner socket":"Yes (IC3)","Stepper IAC mount":"No"}',10);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('v04-pcb','speeduino-v04-pcb','Speeduino v0.4 PCB (DIY Kit)','v0.4 Board','IDC40-based ECU shield — enclosure-friendly with stepper IAC mount. The most popular board.','The v0.4 board routes all I/O through a single IDC40 header (except 12V power), making it ideal for enclosures and interface boards. Includes a DRV8825 stepper driver mount for 4-wire IAC valves. Supports up to 8 cylinders on v0.4.4c+.',14900,'board','["v0.4"]','Stacks onto Arduino Mega 2560','required','[{"boardFamily":["v0.4"]}]','Intermediate','3–7','["Speeduino v0.4 PCB","Through-hole component kit","Assembly guide (PDF)"]','["Arduino Mega 2560","IDC40 plug","Sensors","Wideband controller","Enclosure"]','Most Popular',1,1,'{"Board version":"v0.4.x","I/O connection":"IDC40 header","Injector outputs":"Up to 8 (v0.4.4c+)","Ignition outputs":"Up to 8 (v0.4.4c+)","VR conditioner socket":"Yes (IC3)","Stepper IAC mount":"Yes (DRV8825)"}',20);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('arduino-mega','arduino-mega-2560','Arduino Mega 2560 R3 (ATmega16U2)','Arduino Mega','The controller board for Speeduino. ATmega16U2 USB chip recommended over CH340 clones.','The Arduino Mega 2560 is the brain of every Speeduino build. The official ATmega16U2 variant is recommended by the Speeduino documentation for reliable USB communication. CH340-based clones may require additional drivers and can cause connectivity issues.',4900,'board','["v0.3","v0.4"]','Base board — Speeduino shield stacks on top','required','[]','Beginner','3–5','["Arduino Mega 2560 R3","USB cable"]','[]','Essential',1,1,'{"Processor":"ATmega2560 @ 16 MHz","USB chip":"ATmega16U2 (recommended)","Flash":"256 KB","SRAM":"8 KB","Digital I/O":"54 pins","Analog inputs":"16 pins"}',30);

-- ── MODULES & DRIVERS ───────────────────────────────────────────────────

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('vr-conditioner','vr-conditioner-max9926','VR Conditioner Module (MAX9926)','VR Conditioner','Converts VR crank/cam sine wave to 0–5V square wave. Required for engines with VR sensors.','Variable reluctance (VR) sensors output a sine wave that the Arduino cannot read directly. This dual-channel MAX9926-based conditioner converts the VR signal into a clean 0–5V square wave. Plugs into the IC3 socket on both v0.3 and v0.4 boards.',4500,'module','["v0.3","v0.4"]','IC3 socket on the Speeduino board','required','[{"crankSignal":["vr"]},{"camSignal":["vr"]}]','Beginner','3–7','["MAX9926 dual VR conditioner module"]','[]',NULL,0,1,'{"IC":"MAX9926 dual VR conditioner","Channels":"2 (crank + cam)","Output":"0–5V square wave","Mount":"IC3 DIP socket on board"}',100);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('wideband-controller','wideband-controller-spartan','Wideband Controller (14Point7 Spartan 3 Lite)','Wideband Controller','External wideband AFR controller with 0–5V analog output. Essential for tuning.','Speeduino cannot read wideband O2 sensors directly — an external controller is required. The 14Point7 Spartan 3 Lite reads a Bosch LSU 4.9 sensor and outputs a 0–5V analog signal that Speeduino can read. The single most important tuning tool.',11900,'module','["v0.3","v0.4"]','O2 analog input on the Speeduino board (0–5V)','recommended','[{"o2":["wideband"]}]','Beginner','5–10','["14Point7 Spartan 3 Lite controller"]','["Bosch LSU 4.9 sensor (sold separately)","LSU 4.9 connector (sold separately)"]','Tuning Essential',1,1,'{"Sensor compatibility":"Bosch LSU 4.9","Output":"0–5V analog (linear)","AFR range":"7.35:1 to free air","Power":"12V DC"}',110);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('ignition-driver','ignition-driver-4ch-211','Ignition Driver Module (4-Channel, Bosch 211 Style)','Ignition Driver','Required for dumb coils — amplifies Speeduino''s low-power ignition signals. Do NOT drive dumb coils directly.','Speeduino''s ignition outputs are low-power 5V signals. Dumb coils (without built-in igniters) need an external driver module to switch the high current. Driving dumb coils directly WILL damage the Arduino. This 4-channel Bosch 211-style module handles up to 4 coils.',5900,'module','["v0.3","v0.4"]','Between ECU ignition outputs and coil packs','required','[{"ignitionHardware":["dumb_coils_need_driver"]}]','Intermediate','5–10','["4-channel ignition driver module","Connector pins"]','[]',NULL,0,1,'{"Channels":"4","Style":"Bosch BIP373 / 211 compatible","Input":"5V logic from ECU","Output":"Switched ground to coil negative","Max dwell":"Configurable in TunerStudio"}',120);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('drv8825-stepper','drv8825-stepper-driver','Stepper Driver Module (DRV8825)','DRV8825 Stepper','Stepper motor driver for 4-wire IAC valves. Mounts directly on the v0.4 board.','The DRV8825 stepper motor driver module plugs into the dedicated mount on the v0.4 board, enabling control of 4-wire stepper-type idle air control (IAC) valves. Includes a heatsink for reliable operation.',1200,'module','["v0.4"]','DRV8825 mount on v0.4 board','required','[{"idleControl":["stepper_4wire"],"boardFamily":["v0.4"]}]','Beginner','3–5','["DRV8825 stepper driver module","Heatsink"]','[]',NULL,0,1,'{"IC":"Texas Instruments DRV8825","Max current":"2.5A per coil","Microstepping":"Up to 1/32","Mount":"Dedicated socket on v0.4 board"}',130);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('ballast-resistor','ballast-resistor-pack','Injector Ballast Resistor Pack (4 × 4.7 Ω)','Ballast Resistors','Required for low-impedance injectors. Prevents overcurrent damage to Speeduino driver circuits.','Speeduino''s injector drivers are designed for high-impedance (>8 Ω) injectors. Low-impedance injectors (<5 Ω) draw too much current and will damage the driver circuits. This ballast resistor pack wires in series with each injector to raise the effective impedance to safe levels.',5500,'module','["v0.3","v0.4"]','Inline with each fuel injector','required','[{"injectors":["lowZ"]}]','Intermediate','5–10','["4 × 4.7 Ω ceramic resistors","Mounting hardware"]','[]',NULL,0,1,'{"Resistance":"4.7 Ω per channel","Channels":"4","Power rating":"25W per resistor","Purpose":"Raise low-Z injectors to safe impedance for Speeduino drivers"}',140);

-- ── SENSORS ─────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('map-sensor','map-sensor-mpx4250','MAP Sensor (MPX4250, 2.5 Bar)','MAP Sensor','Recommended MAP sensor for Speeduino. 2.5 bar range covers NA and boosted engines.','The MPX4250 is the recommended MAP sensor in the Speeduino documentation. With a 2.5 bar range it covers naturally aspirated engines and most turbo/supercharged setups. Can be mounted directly on some board variants or remotely via a vacuum hose.',4500,'sensor','["v0.3","v0.4"]','MAP sensor input on the board (onboard mount or remote)','recommended','[]','Beginner','3–7','["MPX4250AP MAP sensor"]','[]',NULL,1,1,'{"Type":"Absolute pressure","Range":"20–250 kPa (2.5 bar)","Output":"0.2–4.9V (ratiometric)","Connector":"3-pin"}',200);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('iat-sensor','iat-sensor-gm','Intake Air Temperature Sensor (GM Open Element)','IAT Sensor','Fast-response open element IAT sensor. Required temp input for accurate fuelling.','A 2-wire GM-style open-element intake air temperature sensor. Required for accurate fuel calculations — the ECU adjusts injector pulse width based on air density. The open element design provides fast response times, ideal for turbocharged applications.',2200,'sensor','["v0.3","v0.4"]','IAT input on the Speeduino board','recommended','[]','Beginner','3–5','["GM open element IAT sensor"]','[]',NULL,0,1,'{"Type":"NTC thermistor (2-wire)","Style":"GM open element","Response":"Fast (open element)","Thread":"3/8 inch push-in or bung mount"}',210);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('clt-sensor','clt-sensor-gm','Coolant Temperature Sensor (GM Style)','CLT Sensor','2-wire GM-style coolant temp sensor. Required for cold-start enrichment and fan control.','A 2-wire GM-style coolant temperature sensor (NTC thermistor). Required for cold-start enrichment, warm-up curves, and temperature-based fan relay activation. The GM calibration is pre-configured in TunerStudio''s default Speeduino settings.',2200,'sensor','["v0.3","v0.4"]','CLT input on the Speeduino board','recommended','[]','Beginner','3–5','["GM-style CLT sensor"]','[]',NULL,0,1,'{"Type":"NTC thermistor (2-wire)","Style":"GM compatible","Thread":"3/8 inch NPT (common adapter sizes available)","Calibration":"Pre-configured in TunerStudio"}',220);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('tps-sensor','tps-sensor-3wire','TPS Sensor (3-Wire Potentiometer)','TPS Sensor','3-wire throttle position sensor. Must be potentiometer type — on/off switches will not work.','Speeduino requires a 3-wire potentiometer-type throttle position sensor (5V, signal, ground). On/off switch-type TPS sensors are NOT compatible. Essential for acceleration enrichment, idle validation, and flood-clear mode. Common on swap builds and individual throttle body (ITB) setups.',3500,'sensor','["v0.3","v0.4"]','TPS input on the Speeduino board','recommended','[]','Beginner','3–7','["3-wire potentiometer TPS"]','[]',NULL,0,1,'{"Type":"Linear potentiometer (3-wire)","Output":"0–5V proportional to throttle angle","Wiring":"5V supply, signal, ground","Note":"On/off switch type NOT compatible"}',230);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('wideband-o2','wideband-o2-lsu49','Wideband O2 Sensor (Bosch LSU 4.9)','WB O2 Sensor','Bosch LSU 4.9 wideband lambda sensor. Pairs with the wideband controller for AFR tuning.','The Bosch LSU 4.9 is the industry standard wideband lambda sensor. It pairs with the Spartan 3 Lite controller (or any LSU 4.9-compatible controller) to provide accurate air-fuel ratio readings across the full operating range. Essential for proper tuning.',12900,'sensor','["v0.3","v0.4"]','Wideband controller (not directly to ECU)','recommended','[{"o2":["wideband"]}]','Beginner','5–10','["Bosch LSU 4.9 wideband O2 sensor"]','["Wideband controller (sold separately)","Exhaust bung"]',NULL,0,1,'{"Type":"Bosch LSU 4.9 (wide-range lambda)","Connector":"6-pin (controller-specific)","Thread":"M18 × 1.5","Cable length":"~1 m"}',240);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('flex-fuel-sensor','flex-fuel-sensor-gm','Flex Fuel Sensor (GM/Continental)','Flex Fuel Sensor','GM/Continental frequency-based ethanol content sensor. 50–150 Hz output for E0–E100.','A GM/Continental flex fuel sensor that measures ethanol content via a frequency output (50 Hz = E0, 150 Hz = E100). Speeduino reads this frequency input and automatically adjusts fuel and ignition maps. Enables running any gasoline/ethanol blend from pump gas to E85+.',19900,'sensor','["v0.3","v0.4"]','Flex fuel input (configured in TunerStudio)','optional','[{"flexFuel":["yes"]}]','Intermediate','5–10','["GM/Continental flex fuel sensor"]','["Fuel line fittings (engine-specific)"]',NULL,0,1,'{"Type":"Frequency-based (GM/Continental)","Output":"50–150 Hz (E0–E100)","Fuel line":"3/8 inch or 5/16 inch (check fitment)","Power":"12V"}',250);

-- ── ACCESSORIES ─────────────────────────────────────────────────────────

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('boost-solenoid','boost-control-solenoid-mac','Boost Control Solenoid (MAC 3-Port)','Boost Solenoid','MAC 3-port boost control solenoid. PWM-driven by the ECU for open or closed-loop boost.','A MAC valve 3-port boost control solenoid for electronic boost control. The ECU drives it via PWM to regulate boost pressure — supports both open-loop and closed-loop (PID) strategies in TunerStudio. The v0.4 board has a dedicated boost output pin.',8900,'accessory','["v0.3","v0.4"]','Boost control output on the ECU','optional','[{"boostControl":["yes"]}]','Intermediate','5–10','["MAC 3-port boost solenoid"]','["Vacuum hose","Fittings"]',NULL,0,1,'{"Type":"3-port / 2-way PWM solenoid","Voltage":"12V","Port size":"1/8 inch NPT","Control":"PWM from ECU boost output"}',300);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('relay-pack','relay-pack-4x-30a','Relay Pack (4 × Bosch 30A 5-Pin + Fuse Box)','Relay Pack','4 × 30A relays + mini fuse box. For fuel pump, ignition, fan, and auxiliary outputs.','Speeduino''s outputs are low-current logic signals — high-current loads like fuel pumps, radiator fans, and ignition power MUST be switched through relays. This pack includes 4 Bosch-style 30A relays and a compact mini-blade fuse box for a clean power distribution setup.',3500,'accessory','["v0.3","v0.4"]','ECU relay outputs','recommended','[]','Beginner','3–5','["4 × Bosch-style 30A 5-pin relays","Mini blade fuse box","Relay socket base"]','[]',NULL,0,1,'{"Relay rating":"30A @ 12V","Relay type":"Bosch-style 5-pin (SPDT)","Fuse box":"4-way mini blade","Typical use":"Fuel pump, ignition, fan, auxiliary"}',310);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('idc40-plug','idc40-plug-pins-v04','IDC40 Plug + Pins (v0.4)','IDC40 Plug','40-pin connector plug for the v0.4 board. Required to wire the board to your engine.','The v0.4 board routes all I/O through a single IDC40 header. This plug + pins set is the #1 blocker for v0.4 builds. Without it, you cannot wire the board to your engine. Crimp pins are included.',900,'accessory','["v0.4"]','IDC40 header on the v0.4 board','required','[{"boardFamily":["v0.4"]}]','Intermediate','3–5','["IDC40 plug housing","40 × crimp pins"]','[]',NULL,0,1,'{"Connector":"IDC40 (40-pin)","Pins":"Crimp-style (included)","Compatibility":"Speeduino v0.4.3, v0.4.4, v0.4.4c"}',320);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('lsu49-connector','lsu49-connector-6pin','LSU 4.9 Wideband Connector (6-Pin)','WB Connector','Connector pigtail for the Bosch LSU 4.9 wideband sensor. Saves sourcing hassle.','A pre-wired 6-pin connector pigtail that mates with the Bosch LSU 4.9 wideband O2 sensor. Eliminates the friction of sourcing the correct connector separately. Short pigtail leads for splicing into your wideband controller wiring.',1400,'accessory','["v0.3","v0.4"]','Bosch LSU 4.9 sensor','optional','[{"o2":["wideband"]}]','Beginner','3–5','["6-pin LSU 4.9 connector pigtail (~15 cm leads)"]','[]',NULL,0,1,'{"Pins":"6","Compatibility":"Bosch LSU 4.9","Lead length":"~15 cm"}',330);

INSERT OR REPLACE INTO products (id, slug, name, short_name, description, long_description, price_eur, category, board_compatibility, connects_to, requirement_level, show_conditions, skill_level, lead_time_days, included, not_included, badge, featured, in_stock, specs, sort_order) VALUES
('coil-connector-pack','smart-coil-connector-pack','Smart Coil Connector Pack (4-Pin, VW/Audi Style)','Coil Connectors','4 × connector pigtails for common smart coils (VW/Audi 4-pin). Optional add-on.','A pack of 4 pre-wired connector pigtails for the ubiquitous VW/Audi-style 4-pin smart ignition coils. These coils are the most commonly used aftermarket COP solution for Speeduino builds. Saves time vs sourcing connectors individually.',900,'accessory','["v0.3","v0.4"]','VW/Audi-style smart coils','optional','[]','Beginner','3–5','["4 × 4-pin coil connector pigtails (~15 cm leads)"]','[]',NULL,0,1,'{"Quantity":"4 connectors","Compatibility":"VW/Audi 4-pin smart coils","Lead length":"~15 cm"}',340);

-- ── INVENTORY ───────────────────────────────────────────────────────────

INSERT OR REPLACE INTO inventory (product_id, qty, updated_at) VALUES
  ('v03-pcb', 100, datetime('now')),
  ('v04-pcb', 100, datetime('now')),
  ('arduino-mega', 100, datetime('now')),
  ('vr-conditioner', 100, datetime('now')),
  ('wideband-controller', 100, datetime('now')),
  ('ignition-driver', 100, datetime('now')),
  ('drv8825-stepper', 100, datetime('now')),
  ('ballast-resistor', 100, datetime('now')),
  ('map-sensor', 100, datetime('now')),
  ('iat-sensor', 100, datetime('now')),
  ('clt-sensor', 100, datetime('now')),
  ('tps-sensor', 100, datetime('now')),
  ('wideband-o2', 100, datetime('now')),
  ('flex-fuel-sensor', 100, datetime('now')),
  ('boost-solenoid', 100, datetime('now')),
  ('relay-pack', 100, datetime('now')),
  ('idc40-plug', 100, datetime('now')),
  ('lsu49-connector', 100, datetime('now')),
  ('coil-connector-pack', 100, datetime('now'));
